### ISSUE TITLE
Default Font on Docz Site not defined

### ISSUE THREAD

**Issue by mark-tate** [mark-tate/use-date-input#13]
Default fonts on the docz site are not defined so it uses Times New Roman

https://mark-tate.github.io/use-date-input/

ACCEPTANCE CRITERIA

Suggest we use the Roboto default font and see how it looks
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />

**Comment by tmarkovic** [comment]
I'd like to work on this
