### ISSUE TITLE
Background color & AnitmatedGroup

### ISSUE THREAD

**Issue by p-j** [mark-tate/use-date-input#22]
Hi 👋🏻 

https://github.com/mark-tate/use-date-input/blob/de568c8c0d6247b23619f08e1c33ec8039d1bfa6/packages/core/src/AnimatedGroup/style.js#L45-L50

I believe there is an issue here, if you override the Root theme by passing a `backgroundColor` instead of a `background` it does not get overridden and stay white which forces to override multiple other components to remove margins & apply the Root BackgroundColor again.

This is somewhat problematic in cases where you don't have full control on the CSS generated.

In the specific case that brought me to trip on this, I was using [`twin.macro`](https://github.com/ben-rogerson/twin.macro) to make use of Tailwind styles.
```
tw`bg-gray-800`
// {
//  --tw-bg-opacity: "1"
//  backgroundColor: "rgba(31, 41, 55, var(--tw-bg-opacity))"
// }
```

Is there a particular reason for this background not to be `transparent` ?
Best

**Comment by p-j** [comment]
Also, I have a question regarding theming, I'm not sure how to customize the date range selection style. Do you have any pointer regarding that?
Thanks

**Comment by mark-tate** [comment]
Hi... If I use `transparent` then you will see dates overlaying each other, during the animation. I could add support for both, if you have used `backgroundColor` in ` theme.calendarOverrides.Root` then use that, else use `background`. Would that work for you ?

**Comment by p-j** [comment]
Yes that would work.

Currently my workaround is to apply the same background color to the `Root` and `MonthRow` as well as remove margin but that also creates some glitches while the animation is in progress, with sometime the month going blank.

**Comment by mark-tate** [comment]
I worked out the issue with dates overlaying and why I added `background`. I've now been able to remove `background` and revert to a `transparent` background. Will try to get a release done before the weekend, which should resolve your issue.

**Comment by p-j** [comment]
Amazing, thanks for the time you spent on that @mark-tate

**Comment by mark-tate** [comment]
see if your problem still exists in version `@use-date-input/core` 0.2.1-beta.0

**Comment by p-j** [comment]
@mark-tate works perfectly !

**Comment by mark-tate** [comment]
great, glad to hear, thanks for raising
